### ISSUE TITLE
Implement all cards component

### ISSUE THREAD

**Issue by poulainv** [poulainv/quiet#10]
Implement cards component of those components

- [x] Movies
- [x] Article 
- [x] Influencers
- [x] Podcast

Then add sample data to display those fixtures in profile!

**Comment by poulainv** [comment]
All pictograms are already committed!

**Comment by deonclem** [comment]
This is the kind of model definition I had in mind:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/1767282/65083937-26cabf80-d9aa-11e9-8fc7-678e0ba61ac3.png">


Any collection should have a type, and we should instantiate its items based on it.

Wdyt?

**Comment by poulainv** [comment]
I commented your commit. I am not fan of those definition as it's really verbose (a bit java style) and define styling (rounded, small, big) inside data... while we rather should use types to decide how we want to display data into card!

**Comment by poulainv** [comment]
Actually, I am not sure that we want different types for now. Maybe
```
{
    title: string
    author: string
    url: string
    imageUrl: string
    type: 'podcast' | 'movie' | 'album' ...
}
```

is enough ... because I don't see any use cases to have `spotifyUrl` | `amazonUrl`! Maybe we can simplify
