### ISSUE TITLE
Item pictogram is weirdly displayed when author is too long

### ISSUE THREAD

**Issue by poulainv** [poulainv/quiet#31]
When the author name is too long, the picto gram is so small!

<img width="265" alt="Screenshot 2019-09-20 at 17 57 45" src="https://user-images.githubusercontent.com/6195703/65342538-3ed15780-dbd3-11e9-8ebc-7bbc2ccf163f.png">

**Comment by deonclem** [comment]
Fixed in #10 (https://github.com/poulainv/quiet/commit/e8cecfed66b13bcea459c0c9fd2055d966f466c2). Closing.
