### ISSUE TITLE
Fix layout issues on Firefox

### ISSUE THREAD

**Issue by deonclem** [poulainv/quiet#41]
On Firefox 68.0.2, the cards aren't properly displayed when clicking "See More":

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/1767282/66270845-37a77c00-e858-11e9-9667-28468f06f659.png">

Also, clicking "See More" on the top section also expands the bottom section, adding a blank space:

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/1767282/66270867-789f9080-e858-11e9-8515-5fd9147d77ea.png">

<img width="907" alt="image" src="https://user-images.githubusercontent.com/1767282/66270881-92d96e80-e858-11e9-8240-e55cf638f5b6.png">

**Comment by poulainv** [comment]
well done!
